### ISSUE TITLE
update link to site generator in README

### ISSUE THREAD

**Issue by sbourdeauducq** [defcon201/site#21]
Happily surprised to see that my crappy script to generate HTML is being useful :)
Anyway it has moved to https://git.m-labs.hk/M-Labs/web

**Comment by sirocyl** [comment]
Oh hey, thanks for the crappy script! <3
We're using it sort of as a stop along the way to a more fully-featured site right now, and plans to extend it are currently on hold.
I've changed the documentation to reflect its new location though, thank you! :)
